name: Generate Keystore Base64

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore my-upload-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass luqapos123 -keypass luqapos123 -dname "CN=Luqa, OU=App, O=Luqa, L=City, S=State, C=US"
      
      - name: Print Keystore Base64
        run: |
          echo "Aquí está tu KEYSTORE_BASE64. Cópialo y pégalo en tus secretos:"
          echo "================================================================="
          base64 my-upload-key.jks | tr -d '\n'
          echo ""
          echo "================================================================="
